
import './globals.css'
import { Roboto_Slab } from 'next/font/google'
// components
import Navbar from './components/navbar'
import SocialLinks from './components/contacts'


const inter = Roboto_Slab({ subsets: ['latin'] })

export const metadata = {
  title: 'Resume',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={inter.className} style={{ 
        backgroundImage: 'url(fischl_bg.jpg)',
        backgroundRepeat: 'no-repeat',
        backgroundColor: '#20246B',
        backgroundSize: '100vw 100vh'
      }}>

        <Navbar />
        {children}
        <SocialLinks/>


      </body>
    </html>
  )
}
